import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex gap-5 bg-slate-600 p-5">
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
            <Link href="/users">Users</Link>
            <Link href="/admins">Admins</Link>
          </nav>
        </header>
        <div className="p-5">{children}</div>
      </body>
    </html>
  );
}
